### ISSUE TITLE
Hello, may I ask you a question?

### ISSUE THREAD

**Issue by 18696232390** [zoomcharts/javascript-charts-library#2]

**Comment by jancha** [comment]
Sure, what's the question?

**Comment by 18696232390** [comment]
Thank you for your reply. My question is that I now want to implement a diffusion graph, which is based on ‘NetCharts’。

Something like that ↓
![image](https://user-images.githubusercontent.com/44156273/88000764-1850b580-cb31-11ea-913c-b3e054a896af.png)


But I've been working on it for a long time, and I've found that the children of the second node, the children of the second node, are evenly spread out over the parent node in a circle, and I just want it to go in one direction。

I read the usage document and found the "link-direction" attribute. After I tried it, I found that it matched the effect I wanted, but it supported up, down, left and right."Top left "," bottom left" and so on are not supported, so please ask if there is any other solution to achieve this effect, or if there is any other API to use, thank you very much!



Thanks again for your reply!

**Comment by 18696232390** [comment]
Sorry, I forgot to include the picture of the current effect

![image](https://user-images.githubusercontent.com/44156273/88001169-12a79f80-cb32-11ea-8a2c-804c90a3f5e9.png)

**Comment by jancha** [comment]
You may want to try the radial layout. It would force the nodes to move out
in a predictable way.

otrd., 2020. g. 21. jūl., plkst. 04:11 — lietotājs Chen (<
notifications@github.com>) rakstīja:

**Comment by 18696232390** [comment]
I just tried the radial layout. Although it can be evenly distributed, when there are too many child nodes, it will still be evenly distributed around the garden, and the graph becomes very rigid, which is not the effect I expected, as shown in the figure

![image](https://user-images.githubusercontent.com/44156273/88036359-06ddcc80-cb76-11ea-9443-94a596efc5db.png)

I would like to have a few more fields in the "link-direction" property

Now it's just "U,R,L,D "and if I could add something like "UR" or "LD" I think that might be a good solution to my problem

**Comment by 18696232390** [comment]
hello,I have other question
please look this photo

![image](https://user-images.githubusercontent.com/44156273/88367963-988c4a80-cdbf-11ea-90f4-5e5135e9d295.png)

this is PieChart ,I hope  text can emmm... look this

![image](https://user-images.githubusercontent.com/44156273/88368214-28ca8f80-cdc0-11ea-87b7-f60f079ff035.png)

how to do that

**Comment by 18696232390** [comment]
have everyone ？

**Comment by 18696232390** [comment]
@jancha hello👀

**Comment by AivisPavlovs** [comment]
@18696232390 you can use pie startAngle setting to achieve this.

https://zoomcharts.com/developers/en/pie-chart/api-reference/settings.html#doc_pie.startAngle

**Comment by AivisPavlovs** [comment]
@18696232390 sorry got the question wrong at first. If you want to adjust the label angle, this can be done via https://zoomcharts.com/developers/en/pie-chart/api-reference/settings/labels.html#doc_angle but this will affect all labels at once.

If you want to have a different angle for each of the labels depending on the position of the slice, you would need to add a style function, where you could calculate the proper angle.

Here is a really simple example - https://jsfiddle.net/n59hb4a7/

**Comment by AivisPavlovs** [comment]
@18696232390 here is an improved sample

https://jsfiddle.net/4evhayr3/

**Comment by 18696232390** [comment]
Thanks for your help, which has solved my problem very well.

**Comment by 18696232390** [comment]
Back to the first question, I want to use a force oriented diagram instead of a tree diagram, so I can't use radial layout. Let me tell you about my current implementation progress, please see the picture 

![image](https://user-images.githubusercontent.com/44156273/88891551-fca68700-d275-11ea-899e-cfe7e5110d72.png)

My business is to express a team, their various organizational management, such as administration, personnel, technology.The big circle represents the team, and the small circles around the big circle represent the organizations.


And from within a department, it extends the people in that department.
![image](https://user-images.githubusercontent.com/44156273/88891778-4db67b00-d276-11ea-9d33-3d4b11971f2a.png)

Here I need to implement the departments and move with the root node.

like this
![image](https://user-images.githubusercontent.com/44156273/88891941-99692480-d276-11ea-94cc-10581a669dcc.png)

Several people around the node, as the root node moves, it does not change relative to the root node, I used here to force the 'x' and 'y' properties of 'to', as shown in the figure
![image](https://user-images.githubusercontent.com/44156273/88892243-11374f00-d277-11ea-9edd-084724c0cacd.png)

In this way, some surrounding nodes can follow the master node, but in this way, the children nodes starting from the "department" node will be evenly distributed around the "department" node. I want them to spread out.

like that [https://zoomcharts.com/developers/en/net-chart/examples/gallery/network-graph-explore-social-links.html](https://zoomcharts.com/developers/en/net-chart/examples/gallery/network-graph-explore-social-links.html)

No matter how far it goes, it always goes out, not in, unless there is a node association.

Now, here's what I look like ↓

![image](https://user-images.githubusercontent.com/44156273/88892695-d255c900-d277-11ea-9501-3c70ae081a3f.png)



This problem has been bothering me for a long time, and I really hope to solve it 😢

**Comment by 18696232390** [comment]
I want to show you that
![image](https://user-images.githubusercontent.com/44156273/88893404-df26ec80-d278-11ea-816e-cd2110237e54.png)

**Comment by AivisPavlovs** [comment]
So this approach is what you are after right?

https://jsfiddle.net/6dp8zu27/

**Comment by 18696232390** [comment]
this is my options
```js
options: {
	layout: {
		crementalLayoutMaxTime: 100,
		initialLayoutMaxTime: 100,
		globalLayoutOnChanges: true,
	},
	interaction: {
		resizing: {
			enabled: true
		},
		selection: {
			allowMoveNodesOffscreen: false,
			tolerance: 1,
		},
	},
	events: {
		onPositionChange: this.movePieCharts,
		onChartUpdate: this.updatePieCharts,
		onClick: this.clickNetCharts,
		onSelectionChange: this.updatePieMenuChart,
	},
	info: {
		enabled: true,
		linkContentsFunction: function(itemData, item) {
			console.log(itemData, item)
			return (
				"<p style='padding-left:5px;padding-right:5px;'>" +
				item.from.label +
				'>' +
				item.label +
				'>' +
				item.to.label +
				'</p></div>'
			)
		},
	},
	navigation: {
		initialNodes: '1',
		mode: focusnodes ', 
		focusNodeExpansionRadius: 400,
		numberOfFocusNodes: 500,
		expandOnClick: true
	},
	style: {
		interaction: {
			resizing: {
				enabled: false,
			},
			selection: {
				lockNodesOnMove: false,
			},
			zooming: {
				zoomExtent: [0.1, 3],
				autoZoomExtent: [1.4, 2],
				autoZoomSize: 1,
				autoZoomAfterClick: true,
			},
		},
		layout: {
			nodeSpacing: 9,
			// aspectRatio: false,
		},
		selection: {
			fillColor: COLORS.COLOR_TM,
		},
		linkAutoScaling: 'logaritmic', // "linear" | "logaritmic"
		selfLinkShape: 'parabolic', // "quadratic" | "parabolic"
		// selfLinkAngle: 20,
		linkStyleFunction: this.linkStyleFunction,
		nodeStyleFunction: this.nodeStyleFunction,
	},
	data: [],
},
```

**Comment by 18696232390** [comment]
I've tried the example link you just sent, but I don't want it to be this way. When the primary node moves, several of its surrounding nodes will also move, which is equivalent to fixing around the root node

**Comment by 18696232390** [comment]
Is it possible to specify that certain nodes use a separate layout? 
![image](https://user-images.githubusercontent.com/44156273/88898695-af2f1780-d27f-11ea-9d29-ab07b704ee3c.png)

**Comment by jancha** [comment]
> Is it possible to specify that certain nodes use a separate layout?
> ![image](https://user-images.githubusercontent.com/44156273/88898695-af2f1780-d27f-11ea-9d29-ab07b704ee3c.png)

Can you prepare a jsfiddle example with the problem? We can look into and try to come up with ideas on how to address the issue you are having.

Thanks,

**Comment by 18696232390** [comment]
Ok, it may take a long time. This is my first time using this tool.

**Comment by jancha** [comment]
> Ok, it may take a long time. This is my first time using this tool.

You can also create sample project in GIT and provide as access to.

**Comment by 18696232390** [comment]
That's a good idea 👍

**Comment by 18696232390** [comment]
My project use a 'VUE-CLI'. Can I use a VUE in the example I gave you?

**Comment by 18696232390** [comment]
It's this framework. Can I build on it? [https://vuejs.org/index.html](https://vuejs.org/index.html)

**Comment by 18696232390** [comment]
Hello, I have created the sample code, please visit [https://github.com/18696232390/zoomchart-buness-demo](https://github.com/18696232390/zoomchart-buness-demo)

start the process：

```
git clone https://github.com/18696232390/zoomchart-buness-demo.git
cd zoomchart-buness-demo/zm-project-demo
npm install 
npm run dev
```

**Comment by 18696232390** [comment]
If you need any help from me, you can always come to me. Thank you very much😊

**Comment by AivisPavlovs** [comment]
Hi @18696232390 

Could you please send me your license key to aivis@zoomcharts.com since this is starting to require more resources from our side, just want to verify the support tier you have available.

Thanks in advance

**Comment by 18696232390** [comment]
Sorry, I don't, I only use and study personally😢

**Comment by 18696232390** [comment]
Is it impossible to get your help without license key    ╥﹏╥...

**Comment by jancha** [comment]
Hi Chen,

Sorry, we have very limited free support available at the moment. However,
looking at the repository here is an idea to avoid cross-linking:

you are already adding the small department nodes on the outer ring of the
root node. What you need to do more is add another similar node further
away and connect all persons to the outer department node, it will force
the layout as you need.

 ![image](https://user-images.githubusercontent.com/540255/89023333-16a2a100-d32c-11ea-814e-a850955b9486.png)

Use link.invisible true, node.invisible true to hide them, however, they
will affect the gravity of the things and you will have perfect layout.

piektd., 2020. g. 31. jūl., plkst. 12:17 — lietotājs Chen (<
notifications@github.com>) rakstīja:

**Comment by 18696232390** [comment]
Thank you very much, this idea may be able to achieve the effect I want, I will try 👍

**Comment by 18696232390** [comment]
This is a bit of a hassle to implement, since you need to insert two lines every time you create a node, which is a bit less user-friendly for deleting nodes. I wonder if there is an easier solution

**Comment by jancha** [comment]
Given your specific layout requirements, this is the best option at the
moment.

piektd., 2020. g. 31. jūl., plkst. 14:37 — lietotājs Chen (<
notifications@github.com>) rakstīja:

**Comment by 18696232390** [comment]
I feel this is also the best solution. Thank you very much!
