### ISSUE TITLE
Dude, I'm back with a problem!

### ISSUE THREAD

**Issue by 18696232390** [zoomcharts/javascript-charts-library#3]

**Comment by 18696232390** [comment]
Now I want to achieve an effect. Based on netChart, after opening the page for the first time, I drag and place a layout. How can I save the position of nodes and leave them in the same place next time when I come in

**Comment by 18696232390** [comment]
![image](https://user-images.githubusercontent.com/44156273/90209226-5a61d400-de1d-11ea-9b07-f408d78e4441.png)

Is this Angle adjustable?

**Comment by 18696232390** [comment]
@jancha

**Comment by 18696232390** [comment]
When I use 'netchart.addData方法', how can I specify the length of the link line? I find that I cannot control the length of the line of the increment node

**Comment by 18696232390** [comment]
When I use  method : 'netchart.addData()', how can I specify the length of the link line? I find that I cannot control the length of the line of the increment node

**Comment by jancha** [comment]
You can specify link.style.length property which is set in relative units,
2 being default. More will make it long less will make it relatively
shorter. Of course forces still play a major role and this property does
not guarantee specific length.

See example: https://jsfiddle.net/d57t62b0/

otrd., 2020. g. 18. aug., plkst. 09:31 — lietotājs Chen (<
notifications@github.com>) rakstīja:

**Comment by jancha** [comment]
Angle is not adjustable, but you can use link direction to push them
together e.g. UDLR
https://zoomcharts.com/developers/en/net-chart/api-reference/settings/style/link.html#doc_direction

piektd., 2020. g. 14. aug., plkst. 06:00 — lietotājs Chen (<
notifications@github.com>) rakstīja:

**Comment by 18696232390** [comment]
"together e.g. UDLR",That means I can use direction="UR" or direction="UL"
