### ISSUE TITLE
Problem for Curves and angles，please！！

### ISSUE THREAD

**Issue by 18696232390** [zoomcharts/javascript-charts-library#4]
Hello..， I received a new request.
- 1. To achieve something similar to a mind map, the root node is on the left and a tree is formed on the right.
- 2. I hope the connection between nodes can be "straight"!.I read the document, but did not find the relevant attributes ~, 
I would like to ask the big guy has a solution ~, thank you ~

img for (1)
![image](https://user-images.githubusercontent.com/44156273/115988692-71340980-a5ed-11eb-978d-25a3047b2bef.png)

img for (2)
![image](https://user-images.githubusercontent.com/44156273/115988652-4ba70000-a5ed-11eb-8e07-a1ae76b8d6ae.png)

**Comment by 18696232390** [comment]
@jancha

**Comment by jancha** [comment]
Hello,
1. Yes, you can set any orientation including horizontal for hierarchy layout by using the "rotation" setting. Please, see: https://zoomcharts.com/developers/en/net-chart/api-reference/settings/layout.html#doc_rotation
2. Unfortunately, orthogonal links are not currently supported.

Regards,
Support Team

________________________________


Begin forwarded message:

From: "Chen.js" ***@***.******@***.***>>
Date: 25 April 2021 at 12:45:52 EEST
To: zoomcharts/javascript-charts-library ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [zoomcharts/javascript-charts-library] Problem for Curves and angles，please！！ (#4)
Reply-To: zoomcharts/javascript-charts-library ***@***.******@***.***>>

﻿

Hello..， I received a new request.

1.       To achieve something similar to a mind map, the root node is on the left and a tree is formed on the right.


[image]<https://user-images.githubusercontent.com/44156273/115988692-71340980-a5ed-11eb-978d-25a3047b2bef.png>




     *   I hope the connection between nodes can be "straight"!.I read the document, but did not find the relevant attributes ~,
I would like to ask the big guy has a solution ~, thank you ~

[image]<https://user-images.githubusercontent.com/44156273/115988652-4ba70000-a5ed-11eb-8e07-a1ae76b8d6ae.png>

**Comment by 18696232390** [comment]
ok， thank you ~
